markdown: rdiscount
pygments: true
exclude: ["README.textile", "config.rb", "sass"]

author: Andreas Karlsson
email: andreas.karlsson@indiebytes.se
github: indiebytes
twitter: andk

url: http://indiebytes.github.com
title: Andreas Karlsson
description: Andreas Karlsson is a web developer living and working in Stockholm, Sweden. On this blog he writes on web development.
permalink: /post/:title.html
future: false